# Generated by Django 3.2 on 2022-01-14 08:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailers', '0002_auto_20220112_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pms_rate', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Fuel: ₦/litre')),
                ('pms_stock', models.BooleanField(default=False)),
                ('ago_rate', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Diesel: ₦/litre')),
                ('ago_stock', models.BooleanField(default=False)),
                ('dpk_rate', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Kerosene: ₦/litre')),
                ('dpk_stock', models.BooleanField(default=False)),
                ('lpg_rate', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Cooking Gas: ₦/kg')),
                ('lpg_stock', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='retailer',
            name='latitude',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)]),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='local_government',
            field=models.CharField(max_length=150, verbose_name='Local Government'),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='longitude',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)]),
        ),
        migrations.AddField(
            model_name='retailer',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='products', to='retailers.Product'),
        ),
    ]
