# Generated by Django 3.2 on 2022-01-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailers', '0003_auto_20220114_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retailer',
            name='products',
        ),
        migrations.AddField(
            model_name='retailer',
            name='ago_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Diesel: ₦/litre'),
        ),
        migrations.AddField(
            model_name='retailer',
            name='ago_stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='retailer',
            name='dpk_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Kerosene: ₦/litre'),
        ),
        migrations.AddField(
            model_name='retailer',
            name='dpk_stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='retailer',
            name='lpg_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Cooking Gas: ₦/kg'),
        ),
        migrations.AddField(
            model_name='retailer',
            name='lpg_stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='retailer',
            name='pms_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Fuel: ₦/litre'),
        ),
        migrations.AddField(
            model_name='retailer',
            name='pms_stock',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
