# Generated by Django 3.2 on 2022-01-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailers', '0004_auto_20220114_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailer',
            name='ago_stock',
            field=models.BooleanField(default=False, verbose_name='Diesel in stock?'),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='dpk_stock',
            field=models.BooleanField(default=False, verbose_name='Kerosene in stock?'),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='lpg_stock',
            field=models.BooleanField(default=False, verbose_name='Cooking Gas in stock?'),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='pms_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Petrol: ₦/litre'),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='pms_stock',
            field=models.BooleanField(default=False, verbose_name='Petrol in stock?'),
        ),
    ]
