# Generated by Django 3.2 on 2022-01-26 08:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailers', '0006_auto_20220124_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailer',
            name='auto_shop',
            field=models.BooleanField(default=False, verbose_name='Auto Shop'),
        ),
        migrations.AddField(
            model_name='retailer',
            name='supermart',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0), django.core.validators.DecimalValidator(decimal_places=6, max_digits=10)]),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0), django.core.validators.DecimalValidator(decimal_places=6, max_digits=10)]),
        ),
    ]
