# Generated by Django 3.2 on 2022-01-30 11:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailers', '0008_auto_20220128_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailer',
            name='car_wash',
            field=models.BooleanField(default=False, verbose_name='Car Wash'),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Kindly input the WGS84 latitude and, restrict the values to a maximum of six decimal places.<br/> Unless you intend to change your location, you can skip this section in the profile page.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0), django.core.validators.DecimalValidator(decimal_places=6, max_digits=10)]),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Kindly input the WGS84 longitude and, restrict the values to a maximum of six decimal places.<br/> Unless you intend to change your location, you can skip this section in the profile page.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0), django.core.validators.DecimalValidator(decimal_places=6, max_digits=10)]),
        ),
    ]
